global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'security'
    static_configs:
      - targets: ['security:3000']
    metrics_path: /metrics

  - job_name: 'uploader'
    static_configs:
      - targets: ['uploader:3000']
    metrics_path: /metrics

  - job_name: 'minio'
    static_configs:
      - targets: ['storage:9000']
    metrics_path: /minio/v2/metrics/cluster

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
