apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-app-chart.fullname" . }}-app
  labels:
    app.kubernetes.io/name: {{ include "demo-app-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "demo-app-chart.name" . }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "demo-app-chart.name" . }}
        app.kubernetes.io/component: app
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: demo-app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.port }}
              protocol: TCP
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.secret.name }}
                  key: SECRET_KEY_BASE
            - name: PHX_HOST
              value: "{{ include "demo-app-chart.fullname" . }}-app"
            - name: PORT
              value: "{{ .Values.app.service.port }}"
            - name: DATABASE_URL
              value: "ecto://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ include "demo-app-chart.fullname" . }}-postgres.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.postgres.auth.database }}"
