apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app-chart.fullname" . }}-app
  labels:
    app.kubernetes.io/name: {{ include "demo-app-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "demo-app-chart.name" . }}
    app.kubernetes.io/component: app
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: 4000
      protocol: TCP
      name: http
