apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-ver-1-26
  namespace: web-ns
data:
  default.conf: |
    server {
      listen 8082;
      server_name _;
      root /usr/share/nginx/html;
      index index.html;
    }
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>My Nginx with ver 1.26</title>
      </head>
      <body>
        <p>Hey, it works!</p>
      </body>
    </html>