---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: production
  namespace: web-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: laura.devops.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nginx-service-ver-1-20
            port:
              number: 80