---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary
  namespace: web-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
spec:
  ingressClassName: nginx
  rules:
  - host: laura.devops.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nginx-service-ver-1-26
            port:
              number: 80